apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rxk41/GitOps.git
    targetRevision: main
    path: k8s-apps/order

  destination:
    server: https://kubernetes.default.svc
    namespace: microservices

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true