apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-v1
  namespace: microservices
  labels:
    app: order
    version: v1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order
      version: v1

  template:
    metadata:
      labels:
        app: order
        version: v1

    spec:
      containers:
        - name: order
          image: hashicorp/http-echo:1.0

          args:
            - "-text=Hello from Order Service: v1"
            - "-listen=:8080"

          ports:
            - name: http
              containerPort: 8080

          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 20
