name: Kubernetes CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install kubeconform
        run: |
          curl -L -o kubeconform.tar.gz \
            https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz

          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/kubeconform

      - name: Validate Kubernetes manifests
        run: |
          kubeconform \
            -strict \
            -summary \
            -output text \
            k8s-apps/frontend/*.yaml \
            k8s-apps/product/*.yaml \
            k8s-apps/order/*.yaml \
            k8s-platform/istio/*.yaml

      - name: Validate Istio manifests
        run: |
          kubeconform \
            -strict \
            -summary \
            -output text \
            -schema-location default \
            k8s-platform/Gateway/*.yaml